import { LegalLayout, List, Section } from "./LegalLayout";

export function Terms() {
  return (
    <LegalLayout
      title="Terms of Service"
      intro="The agreement between you and agenticcore.click when you use the service."
    >
      <Section heading="What the service is">
        <p>
          agenticcore.click produces business assets to order — websites, documents, images, video,
          social content and brand material. Work is generated by automated systems, reviewed
          against the specification for the product you bought, and delivered to your dashboard.
        </p>
        <p>
          You are buying a specific product with a defined output, not open-ended creative labour.
          What each product includes, and how many revisions come with it, is stated on its page
          before you order.
        </p>
      </Section>

      <Section heading="Your account">
        <p>
          You need an account to order. Keep your password to yourself — anything ordered from your
          account is treated as ordered by you, and your wallet is charged accordingly. Tell us
          promptly if you think someone else has access.
        </p>
        <p>One person or business per account. Don't share logins across organisations.</p>
      </Section>

      <Section heading="Paying">
        <p>
          The service runs on a prepaid wallet. You top the wallet up, and each order is charged
          against the balance at the price shown when you confirm. If the balance doesn't cover an
          order, the order isn't created and nothing is charged.
        </p>
        <p>Prices are in US dollars and can change, but never for an order already placed.</p>
      </Section>

      <Section heading="What you get, and what you own">
        <p>
          Once an order is delivered and paid for, the output is yours. You can use it commercially,
          modify it, and publish it, with no further payment or attribution to us.
        </p>
        <p>
          Two honest limits on that. Automated generation can produce output resembling other work,
          so we cannot promise any deliverable is unique or registrable as a trademark — check
          before you build a brand on one. And you keep ownership of anything you supply: your
          logos, photos, text and brand material stay yours, and you grant us only the permission
          needed to produce your order.
        </p>
      </Section>

      <Section heading="What you must not order">
        <p>Don't use the service to produce:</p>
        <List
          items={[
            "anything unlawful where you are, or where it will be published",
            "material that impersonates a real person or organisation, including by using their name, branding or domain",
            "content designed to deceive — fake reviews, fabricated records, or pages that collect passwords or payment details under false pretences",
            "material that harasses or targets a private individual",
            "work built on material you have no right to use",
          ]}
        />
        <p>
          We can decline or cancel an order on these grounds and refund it. Repeated attempts end
          the account.
        </p>
      </Section>

      <Section heading="Turnaround">
        <p>
          Stated turnarounds are what we build against, not guarantees. Most orders complete in
          minutes. Some need information we don't have, in which case the order pauses and your
          dashboard says what's missing.
        </p>
      </Section>

      <Section heading="Revisions">
        <p>
          Revisions included with a product are shown on the order and can be requested from your
          dashboard. Products that return several options to choose from — images and video among
          them — include none, because choosing between the options is the revision. This is stated
          before you buy.
        </p>
      </Section>

      <Section heading="Availability">
        <p>
          We aim to keep the service running but don't promise uninterrupted availability. The
          service depends on third-party providers, and an outage at one of them can stop orders
          being produced. Where an outage prevents delivery, see the refund policy.
        </p>
      </Section>

      <Section heading="Limits on liability">
        <p>
          The service is provided as-is. To the extent the law allows, our total liability for any
          claim is limited to what you paid for the order the claim concerns.
        </p>
        <p>
          You are responsible for reviewing deliverables before using them. Automated output can
          contain errors of fact, and we are not liable for loss arising from published work you
          did not check.
        </p>
      </Section>

      <Section heading="Ending the agreement">
        <p>
          You can stop using the service at any time and request any unused wallet balance back.
          We can suspend or close an account that breaches these terms; where we do, any unused
          balance is returned unless it relates to the breach.
        </p>
      </Section>

      <Section heading="Changes and contact">
        <p>
          We may update these terms. Material changes will be shown on the site, and the date at
          the top always reflects the current version. Continuing to use the service after a change
          means you accept it.
        </p>
        <p>
          Questions: <a className="text-yellow-400 hover:underline" href="mailto:hello@agenticcore.click">hello@agenticcore.click</a>
        </p>
      </Section>
    </LegalLayout>
  );
}
